_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 51
                - 53
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
            "3":
                - 16
                - 55
            "4": 3.8.20
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
activation:
    value: tanh
backbone:
    value: MLP
batch_size:
    value: 256
checkpoints:
    value: ./checkpoints
d_hid:
    value: 1024
dataset:
    value: metabric
dropout:
    value: 0
epochs:
    value: 100
feature_file:
    value: ./datasets/METABRIC/cleaned_features_final.csv
kfold:
    value: 5
label_file:
    value: ./datasets/METABRIC/label.csv
lr:
    value: 0.0002
lr_policy:
    value: cosine
method:
    value: ordsurv
n_layers:
    value: 2
normalize:
    value: false
optimizer:
    value: Adam
results:
    value: ./results
seed:
    value: 42
step:
    value: 7
stratify:
    value: true
task:
    value: survival
verbose:
    value: true
visible_gpus:
    value: "1"
weight_decay:
    value: 0.01
workers:
    value: 0
