# environment
visible_gpus: '0'
seed: 42

# dataset
dataset: 'nwtco'
task: 'survival'
checkpoints: './checkpoints'
results: './results'

kfold: 5
stratify: True
step: 30. # step for time bin discretization in days
normalize: False

# model
method: 'ordsurv' # 'ordsurv', 'deephit', 'deepsurv', 'discrete', 'angularord', 'ordsoftmax'
backbone: 'MLP'
n_layers: 2
d_hid: 1024
dropout: 0.
activation: 'tanh'


# training
workers: 0
optimizer: 'Adam'
epochs: 100
batch_size: 256
lr: 5.0e-5
lr_policy: 'cosine'
weight_decay: 0.01
verbose: True
